name: testcfg
dataset: normal # one of: [normal, rotation]
use_cubes: True # whether to use a background
n_lobes: 5
training: 
    render_interval: 1                  # interval at which the current batch should be rendered to a file
    render_cols: 10                     # number of columns to be used for the rendered image grid
    checkpoint_interval: 20             # interval at which a checkpoint of the network should be saved
    n_image_per_batch: 30               # batch size during training
    lr: 0.0001                           # learning rate
    compute_velocity_seperately: True   
    n_pts_per_split: 2048
    sampling_lvl_for_vel_loss: 5
    n_iterations: 1000
    rand_seed: 0
    vertex_grad_clip: 0.1
sampling:
    ico_sphere_level: 6
    T: 20
rendering:
    rgb: 
        image_size: 100                 # image resolution
        blur_radius: 0.0
        faces_per_pixel: 4
        max_intensity: 1. #######   read_ing:0.09, budd_ha: 0.15, pot_2: 0.15, co_w: 0.15, bea_r:  0.2
        sigma: 0.0001
        gamma: 0.0001 #######
        L0: None
        crop: False # Set to True if you want to render only a subregion of the image
        crop_ratio: 0.5 # Ratio of the image to keep when cropping
    silhouette:
        image_size: 100 #######
        blur_radius: 0.1 #######
        faces_per_pixel: 100
        sigma: 0.0001
        gamma: 0.0001
validation: 
    angle: None                     # specify an angle of viewpoints
    interval: 20      # interval at which a validation of the network is applied
    early_stopping: False
    early_stopping_patience: 1
loss:   # loss weights
    lambda_image: 1.0
    lambda_silhouette: 0 #1.0 #######
    lambda_velocity: 0.1 # 0.1
    alpha: 0 # 0.05
    lambda_edge: 0 #0.5
    lambda_normal_consistency: 0 #0.5
    lambda_laplacian_smoothing: 0 #0.5